server:
  port: 8080
  address: 0.0.0.0

topic:
  name: smsr3

spring:
  data:
    mongodb:
      uri: mongodb://root:Rm3MpB4vR5AXPL@172.22.4.106:6400/MDMQ_NOTIFICACIONES_CORREO?authSource=admin
  kafka:
    bootstrap-server: 172.22.4.106:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
